### ISSUE TITLE
The authentication dont work (KeyError: 'picture')

### ISSUE THREAD

**Issue by 9acca9** [tehkillerbee/mopidy-tidal#114]
I go to the link and im getting this error:

```
May 08 21:09:52 raspberrypi mopidy[7920]: INFO     [TidalBackend-4] mopidy_tidal.backend Visit link.tidal.com/COACV to log in, the code will expire in 300 seconds
May 08 21:10:41 raspberrypi mopidy[7920]: ERROR    [TidalBackend-4] pykka Unhandled exception in TidalBackend (urn:uuid:439f4d8d-565c-41df-bf81-3037cad1e31d):
May 08 21:10:41 raspberrypi mopidy[7920]: Traceback (most recent call last):
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 186, in _actor_loop
May 08 21:10:41 raspberrypi mopidy[7920]:     self.on_start()
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_tidal/backend.py", line 83, in on_start
May 08 21:10:41 raspberrypi mopidy[7920]:     self.oauth_login_new_session(oauth_file)
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/local/lib/python3.9/dist-packages/mopidy_tidal/backend.py", line 29, in oauth_login_new_session
May 08 21:10:41 raspberrypi mopidy[7920]:     self._session.login_oauth_simple(function=logger.info)
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/local/lib/python3.9/dist-packages/tidalapi/session.py", line 323, in login_oauth_simple
May 08 21:10:41 raspberrypi mopidy[7920]:     future.result()
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 440, in result
May 08 21:10:41 raspberrypi mopidy[7920]:     return self.__get_result()
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
May 08 21:10:41 raspberrypi mopidy[7920]:     raise self._exception
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
May 08 21:10:41 raspberrypi mopidy[7920]:     result = self.fn(*self.args, **self.kwargs)
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/local/lib/python3.9/dist-packages/tidalapi/session.py", line 364, in _process_link_login
May 08 21:10:41 raspberrypi mopidy[7920]:     self.user = tidalapi.User(self, user_id=json['userId']).factory()
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/local/lib/python3.9/dist-packages/tidalapi/user.py", line 48, in factory
May 08 21:10:41 raspberrypi mopidy[7920]:     return self.request.map_request('users/%s' % self.id, parse=self.parse)
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/local/lib/python3.9/dist-packages/tidalapi/request.py", line 118, in map_request
May 08 21:10:41 raspberrypi mopidy[7920]:     return self.map_json(json_obj, parse=parse)
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/local/lib/python3.9/dist-packages/tidalapi/request.py", line 125, in map_json
May 08 21:10:41 raspberrypi mopidy[7920]:     return parse(json_obj)
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/local/lib/python3.9/dist-packages/tidalapi/user.py", line 65, in parse
May 08 21:10:41 raspberrypi mopidy[7920]:     return user.parse(json_obj)
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/local/lib/python3.9/dist-packages/tidalapi/user.py", line 104, in parse
May 08 21:10:41 raspberrypi mopidy[7920]:     super(LoggedInUser, self).parse(json_obj)
May 08 21:10:41 raspberrypi mopidy[7920]:   File "/usr/local/lib/python3.9/dist-packages/tidalapi/user.py", line 77, in parse
May 08 21:10:41 raspberrypi mopidy[7920]:     self.picture_id = json_obj['picture']
May 08 21:10:41 raspberrypi mopidy[7920]: KeyError: 'picture'
May 08 21:10:41 raspberrypi mopidy[7920]: ERROR    [MainThread] mopidy.commands Actor died: TidalBackend (urn:uuid:439f4d8d-565c-41df-bf81-3037cad1e31d) stopped before handling the message

```

This is running in a server without desktop so i go to the link from other pc (i suppose that this cant be a problem, but just saying).
What can i do to fix this? 
Thanks!

p.s.: by the way, this file is never created 
`var/lib/mopidy/tidal/tidal-oauth.json: [Errno 2] No such file or directory: '/var/lib/mopidy/tidal/tidal-oauth.json'
`

**Comment by tehkillerbee** [comment]
Hello, please refer to the issue here as this issue is unfortunately related to the tidalapi https://github.com/tehkillerbee/mopidy-tidal/issues/97.

You will need to install the tidalapi fork by @BlackLight 
```
sudo pip3 uninstall tidalapi
sudo pip3 install git+https://github.com/BlackLight/mopidy-tidal
```

**Comment by 9acca9** [comment]
Oh, thanks! Now is working!
