### ISSUE TITLE
No images exist for certain library folders (genres, moods, mixes, my_artists, .. ) resulting in error

### ISSUE THREAD

**Issue by valmar** [tehkillerbee/mopidy-tidal#120]
I would like to report an error that I see in the mopidy logs when browsing Tidal. This does not seem to prevent Tidal from working, however.

Software versions are: 

Mopidy 3.4.1, Mopidy-Tidal 0.3.2, tidalapi 0.7.1

Let me  know if I can help with testing, etc., and thank you for developing Mopidy-Tidal!

```
INFO     2023-06-01 22:55:32,608 [1:TidalBackend-3] mopidy_tidal.library
  Searching Tidal for images for ['tidal:genres', 'tidal:moods', 'tidal:mixes', 'tidal:my_artists', 'tidal:my_albums', 'tidal:my_playlists', 'tidal:my_tracks']
ERROR    2023-06-01 22:55:32,610 [1:Core-8] mopidy.core.library
  TidalBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 17, in _backend_error_handling
    yield
  File "/usr/lib/python3/dist-packages/mopidy/core/library.py", line 194, in get_images
    if future.get() is None:
  File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mopidy_tidal/library.py", line 259, in get_images
    images = {uri: item_images for uri, item_images in pool_res}
  File "/usr/local/lib/python3.9/dist-packages/mopidy_tidal/library.py", line 259, in <dictcomp>
    images = {uri: item_images for uri, item_images in pool_res}
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 600, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mopidy_tidal/library.py", line 99, in __call__
    return uri, self._get_images(uri)
  File "/usr/local/lib/python3.9/dist-packages/mopidy_tidal/library.py", line 72, in _get_images
    item_id = parts[2]
IndexError: list index out of range
```

**Comment by tehkillerbee** [comment]
Hello @valmar and thanks for taking your time to report this issue.

I have also noticed the issue and I have been working on a quick fix that should be implemented in the next release.

The issue stems from certain folders ('tidal:genres', 'tidal:moods', 'tidal:mixes', 'tidal:my_artists', 'tidal:my_albums', 'tidal:my_playlists', 'tidal:my_tracks') not having any images associated to them. The current mopidy-tidal logic tries to fetch images for all folders, using the same logic as used for albums, tracks etc.

**Comment by valmar** [comment]
@tehkillerbee Thank you for looking into this. Please rely on me to help with testing fixes, if you need help: I am a software developer

**Comment by tehkillerbee** [comment]
Fixed when  https://github.com/tehkillerbee/mopidy-tidal/pull/131 is merged

**Comment by tehkillerbee** [comment]
> @tehkillerbee Thank you for looking into this. Please rely on me to help with testing fixes, if you need help: I am a software developer

Thank you! The feature should now be merged in. Let me know if you notice any similar errors.
