### ISSUE TITLE
KeyError: 'gender'

### ISSUE THREAD

**Issue by NicoJusso** [tehkillerbee/mopidy-tidal#122]
Hello,

From today, I have this bug :

```
ERROR    2023-07-05 15:26:22,915 [5532:TidalBackend-6 (_actor_loop)] pykka                                                                                                                    
  Unhandled exception in TidalBackend (urn:uuid:23ca39a5-11f1-4135-9379-b5d1a90b2c61):                                                                                                        
Traceback (most recent call last):                                                                                                                                                            
  File "/usr/local/lib/python3.10/dist-packages/pykka/_actor.py", line 179, in _actor_loop                                                                                                    
    self.on_start()                                                                                                                                                                           
  File "/usr/local/lib/python3.10/dist-packages/mopidy_tidal/backend.py", line 83, in on_start                                                                                                
    self.oauth_login_new_session(oauth_file)                                                                                                                                                  
  File "/usr/local/lib/python3.10/dist-packages/mopidy_tidal/backend.py", line 29, in oauth_login_new_session                                                                                 
    self._session.login_oauth_simple(function=logger.info)
  File "/usr/local/lib/python3.10/dist-packages/tidalapi/session.py", line 323, in login_oauth_simple
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs) 
  File "/usr/local/lib/python3.10/dist-packages/tidalapi/session.py", line 364, in _process_link_login
    self.user = tidalapi.User(self, user_id=json['userId']).factory()
  File "/usr/local/lib/python3.10/dist-packages/tidalapi/user.py", line 48, in factory
    return self.request.map_request('users/%s' % self.id, parse=self.parse)
  File "/usr/local/lib/python3.10/dist-packages/tidalapi/request.py", line 118, in map_request
    return self.map_json(json_obj, parse=parse) 
  File "/usr/local/lib/python3.10/dist-packages/tidalapi/request.py", line 125, in map_json
    return parse(json_obj)
  File "/usr/local/lib/python3.10/dist-packages/tidalapi/user.py", line 65, in parse
    return user.parse(json_obj)
  File "/usr/local/lib/python3.10/dist-packages/tidalapi/user.py", line 110, in parse
    self.gender = json_obj['gender']
KeyError: 'gender'
ERROR    2023-07-05 15:26:22,918 [5532:MainThread] mopidy.commands
  Actor died: TidalBackend (urn:uuid:23ca39a5-11f1-4135-9379-b5d1a90b2c61) stopped before handling the message
```

**Comment by tehkillerbee** [comment]
Thanks.

Looks like TIDAL changed something again.

Take a look here and see if the suggested solution works:
https://github.com/tamland/python-tidal/issues/146

Change

self.gender = json_obj["gender"]

to

self.gender = json_obj.get("gender", None)

**Comment by tehkillerbee** [comment]
This is now fixed on latest tidalapi master. We will release an updated version soon, when a few other issues are merged in.

https://github.com/tamland/python-tidal/issues/146#event-9745242664

**Comment by tehkillerbee** [comment]
PyPi package for tidalapi has now been updated to the latest release. Please make sure you upgrade to latest v0.7.2 release. Marking this issue as fixed.
