### ISSUE TITLE
AttributeError: partially initialized module 'tidalapi' has no attribute 'session' 

### ISSUE THREAD

**Issue by tehkillerbee** [tehkillerbee/mopidy-tidal#124]
Using latest tidalapi results in an error:
```
lip 12 10:29:51 cezdro mopidy[1183304]: Traceback (most recent call last):
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/mopidy/__main__.py", line 129, in main
lip 12 10:29:51 cezdro mopidy[1183304]:     extension.setup(registry)
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/mopidy_tidal/__init__.py", line 37, in setup
lip 12 10:29:51 cezdro mopidy[1183304]:     from .backend import TidalBackend
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/mopidy_tidal/backend.py", line 9, in <module>
lip 12 10:29:51 cezdro mopidy[1183304]:     from tidalapi import Config, Quality, Session
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/tidalapi/__init__.py", line 4, in <module>
lip 12 10:29:51 cezdro mopidy[1183304]:     from .media import Track, Video  # noqa: F401
lip 12 10:29:51 cezdro mopidy[1183304]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/tidalapi/media.py", line 34, in <module>
lip 12 10:29:51 cezdro mopidy[1183304]:     class Media:
lip 12 10:29:51 cezdro mopidy[1183304]:   File "/home/cezdro/.local/pipx/venvs/mopidy/lib/python3.11/site-packages/tidalapi/media.py", line 63, in Media
lip 12 10:29:51 cezdro mopidy[1183304]:     self, session: tidalapi.session.Session, media_id: Optional[str] = None
lip 12 10:29:51 cezdro mopidy[1183304]:                    ^^^^^^^^^^^^^^^^
lip 12 10:29:51 cezdro mopidy[1183304]: AttributeError: partially initialized module 'tidalapi' has no attribute 'session' (most likely due to a circular import)
```

Also reported here: https://github.com/tamland/python-tidal/issues/156

**Comment by tehkillerbee** [comment]
Cannot replicate, appears fixed in latest tidalapi master. Closing
