### ISSUE TITLE
lru_cache error in Mopidy 3

### ISSUE THREAD

**Issue by greggilbert** [tehkillerbee/mopidy-tidal#14]
Edit: I had a different question here before, so I'm reusing the issue.

I've got Mopidy 3 running in a virtualenv with Python 3.8 on Ubuntu 18.04. When I try to start Mopidy with this extension installed, I get this error:

```
ERROR    2020-02-27 00:39:22,235 [15843:MainThread] mopidy.__main__
  Extension tidal failed during setup. This might have left the registry in a bad state.
Traceback (most recent call last):
  File "/srv/mopidy/_venv/lib/python3.8/site-packages/mopidy/__main__.py", line 129, in main
    extension.setup(registry)
  File "/srv/mopidy/_venv/lib/python3.8/site-packages/mopidy_tidal/__init__.py", line 33, in setup
    from .backend import TidalBackend
  File "/srv/mopidy/_venv/lib/python3.8/site-packages/mopidy_tidal/backend.py", line 11, in <module>
    from mopidy_tidal import library, playback, playlists
  File "/srv/mopidy/_venv/lib/python3.8/site-packages/mopidy_tidal/library.py", line 15, in <module>
    from mopidy_tidal.search import tidal_search
  File "/srv/mopidy/_venv/lib/python3.8/site-packages/mopidy_tidal/search.py", line 7, in <module>
    from lru_cache import SearchCache
ModuleNotFoundError: No module named 'lru_cache'
```

I have lru_cache installed, though:

```
# python -m pip show lru_cache
Name: lru-cache
Version: 0.2.3
Summary: thread safe lru cache
Home-page: https://github.com/acmerfight/lru_cache
Author: acmerfight
Author-email: acmerfight@gmail.com
License: MIT
Location: /srv/mopidy/_venv/lib/python3.8/site-packages
Requires:
```

Any idea what's up?

**Comment by greggilbert** [comment]
Actually.. closing this for now. I think it's an issue with how I'm running Mopidy.

**Comment by greggilbert** [comment]
Update: I just needed to use the latest version (i.e. not the one in pypi).

If anyone else finds this, I solved this by running `pip install --upgrade git+https://github.com/tehkillerbee/mopidy-tidal.git@master`
