### ISSUE TITLE
500 errors on API calls to Tidal

### ISSUE THREAD

**Issue by BlackLight** [tehkillerbee/mopidy-tidal#146]
Is it only me or the playback API seems to be suddenly broken?

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/core/playback.py", line 352, in _change
    if not backend.playback.change_track(pending_tl_track.track).get():
  File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/lib/python3/dist-packages/mopidy/backend.py", line 331, in change_track
    uri = self.translate_uri(track.uri)
  File "/usr/local/lib/python3.9/dist-packages/mopidy_tidal/login_hack.py", line 306, in wrapper
    return fn(obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mopidy_tidal/playback.py", line 27, in translate_uri
    newurl = session.track(track_id).get_url()
  File "/usr/local/lib/python3.9/dist-packages/tidalapi/session.py", line 493, in track
    item = tidalapi.Track(session=self, media_id=track_id)
  File "/usr/local/lib/python3.9/dist-packages/tidalapi/media.py", line 62, in __init__
    self._get(self.id)
  File "/usr/local/lib/python3.9/dist-packages/tidalapi/media.py", line 161, in _get
    return self.requests.map_request('tracks/%s' % media_id, parse=parse)
  File "/usr/local/lib/python3.9/dist-packages/tidalapi/request.py", line 116, in map_request
    json_obj = self.request('GET', url, params).json()
  File "/usr/local/lib/python3.9/dist-packages/tidalapi/request.py", line 99, in request
    request.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.tidal.com/v1/tracks/...?sessionId=...&countryCode=NL&limit=1000
```

**Comment by BlackLight** [comment]
Nevermind, the problem went away as fast as it came in.

It seemed that something broke on Tidal's side though, as for ~20 minutes playback features were broken also on the web player and the app.
