### ISSUE TITLE
Extension failed during setup

### ISSUE THREAD

**Issue by jaedb** [tehkillerbee/mopidy-tidal#16]
After installing with `python3.7 -m pip install Mopidy-Tidal` I cannot seem to get Tidal to start up with the rest of Mopidy. All I observe is a startup error as below:
```
ERROR    2020-04-28 22:06:05,493 [6:MainThread] mopidy.__main__
  Extension tidal failed during setup. This might have left the registry in a bad state.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/Mopidy-3.0.1-py3.7.egg/mopidy/__main__.py", line 129, in main
    extension.setup(registry)
  File "/usr/local/lib/python3.7/site-packages/mopidy_tidal/__init__.py", line 33, in setup
    from .backend import TidalBackend
  File "/usr/local/lib/python3.7/site-packages/mopidy_tidal/backend.py", line 11, in <module>
    from mopidy_tidal import library, playback, playlists
  File "/usr/local/lib/python3.7/site-packages/mopidy_tidal/library.py", line 15, in <module>
    from mopidy_tidal.search import tidal_search
  File "/usr/local/lib/python3.7/site-packages/mopidy_tidal/search.py", line 7, in <module>
    from lru_cache import SearchCache
ModuleNotFoundError: No module named 'lru_cache'
```

**Comment by jaedb** [comment]
Duplicate of #14
