### ISSUE TITLE
mopidy-tidal don't work today

### ISSUE THREAD

**Issue by chicco64** [tehkillerbee/mopidy-tidal#50]
Hi !
from today the player does not connect to Tidal
if you can check....
thank you

**Comment by tehkillerbee** [comment]
@chicco64 This issue is still related to #49 so closing this issue

**Comment by tehkillerbee** [comment]
Reopening, in case this is in fact yet another API key change

**Comment by chicco64** [comment]
Feb 01 10:03:13 debian10 mopidy[13176]: INFO     [TidalBackend-5] mopidy_tidal.backend Creating new OAuth session...
Feb 01 10:03:14 debian10 mopidy[13176]: ERROR    [TidalBackend-5] tidalapi Login failed: {"status":401,"error":"invalid_client","sub_status":1005,"error_description":"Client with token 8SEZWa4J1NVC5U5Y not found"}
Feb 01 10:03:14 debian10 mopidy[13176]: ERROR    [TidalBackend-5] pykka Unhandled exception in TidalBackend (urn:uuid:e14aaa8e-c336-4476-873f-ab913dc05290):
Feb 01 10:03:14 debian10 mopidy[13176]: Traceback (most recent call last):
Feb 01 10:03:14 debian10 mopidy[13176]:   File "/usr/local/lib/python3.7/dist-packages/pykka/_actor.py", line 179, in _actor_loop
Feb 01 10:03:14 debian10 mopidy[13176]:     self.on_start()
Feb 01 10:03:14 debian10 mopidy[13176]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_tidal/backend.py", line 84, in on_start
Feb 01 10:03:14 debian10 mopidy[13176]:     self.oauth_login_new_session(oauth_file)
Feb 01 10:03:14 debian10 mopidy[13176]:   File "/usr/local/lib/python3.7/dist-packages/mopidy_tidal/backend.py", line 33, in oauth_login_new_session
Feb 01 10:03:14 debian10 mopidy[13176]:     self._session.login_oauth_simple(function=logger.info)
Feb 01 10:03:14 debian10 mopidy[13176]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/__init__.py", line 213, in login_oauth_simple
Feb 01 10:03:14 debian10 mopidy[13176]:     login, future = self.login_oauth()
Feb 01 10:03:14 debian10 mopidy[13176]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/__init__.py", line 226, in login_oauth
Feb 01 10:03:14 debian10 mopidy[13176]:     login, future = self._login_with_link()
Feb 01 10:03:14 debian10 mopidy[13176]:   File "/usr/local/lib/python3.7/dist-packages/tidalapi/__init__.py", line 240, in _login_with_link
Feb 01 10:03:14 debian10 mopidy[13176]:     request.raise_for_status()
Feb 01 10:03:14 debian10 mopidy[13176]:   File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 960, in raise_for_status
Feb 01 10:03:14 debian10 mopidy[13176]:     raise HTTPError(http_error_msg, response=self)
Feb 01 10:03:14 debian10 mopidy[13176]: requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://auth.tidal.com/v1/oauth2/device_authorization
Feb 01 10:03:14 debian10 mopidy[13176]: ERROR    [MainThread] mopidy.commands Actor died: TidalBackend (urn:uuid:e14aaa8e-c336-4476-873f-ab913dc05290) stopped before handling the message
Feb 01 10:03:14 debian10 mopidy[13176]: INFO     [MainThread] mopidy.commands Starting Mopidy core
Feb 01 10:03:14 debian10 mopidy[13176]: INFO     [MainThread] mopidy.commands Starting Mopidy frontends: MpdFrontend, HttpFrontend
Feb 01 10:03:14 debian10 mopidy[13176]: INFO     [MainThread] mopidy_mpd.actor MPD server running at [::ffff:127.0.0.1]:6600
Feb 01 10:03:14 debian10 mopidy[13176]: INFO     [HttpFrontend-9] mopidy.http.actor HTTP server running at [::ffff:0.0.0.0]:6680
Feb 01 10:03:14 debian10 mopidy[13176]: INFO     [MainThread] mopidy.commands Starting GLib mainloop

**Comment by tehkillerbee** [comment]
@chicco64 Yep, it looks like the API key is not valid any longer.

**Comment by chicco64** [comment]
Hi! do you have any updates for system restore? Many thanks
