### ISSUE TITLE
Tidal backend caused an exception

### ISSUE THREAD

**Issue by fmarzocca** [tehkillerbee/mopidy-tidal#62]
During a playlst play I got this error:

`2022-05-23 11:26:39,328 ERROR [1066:Core-17] mopidy.core.playback: TidalBackend backend caused an exception.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/core/playback.py", line 203, in _on_about_to_finish
    if backend.playback.change_track(pending.track).get():
  File "/usr/lib/python3/dist-packages/pykka/_threading.py", line 45, in get
    _compat.reraise(*self._data['exc_info'])
  File "/usr/lib/python3/dist-packages/pykka/_compat/__init__.py", line 29, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 193, in _actor_loop
    response = self._handle_receive(envelope.message)
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 299, in _handle_receive
    return callee(*message.args, **message.kwargs)
  File "/usr/lib/python3/dist-packages/mopidy/backend.py", line 315, in change_track
    uri = self.translate_uri(track.uri)
  File "/usr/local/lib/python3.7/dist-packages/mopidy_tidal/playback.py", line 16, in translate_uri
    newurl = self.backend._session.get_media_url(track_id)
  File "/usr/local/lib/python3.7/dist-packages/tidalapi/__init__.py", line 496, in get_media_url
    request = self.request('GET', 'tracks/%s/urlpostpaywall' % track_id, params)
  File "/usr/local/lib/python3.7/dist-packages/tidalapi/__init__.py", line 361, in request
    request.raise_for_status()
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.tidalhifi.com/v1/tracks/174
661866/urlpostpaywall?sessionId=...........&countryCode=IT&limit=999&urlusagemode=STR
EAM&audioquality=LOSSLESS&assetpresentation=FULL`

**Comment by tehkillerbee** [comment]
Could you continue playing afterwards? Is it a specific album/song?

**Comment by fmarzocca** [comment]
No, it blocks playing. It happened on a Tidal playlist and I am keep watching if it happens again on others.
