### ISSUE TITLE
OAuth seems to be broken

### ISSUE THREAD

**Issue by Simerax** [tehkillerbee/mopidy-tidal#97]
Newest Version of Mopidy and newest Version of Mopidy-Tidal:

```
Mär 15 10:48:54 fxlaptop mopidy[59707]:   Visit link.tidal.com/ABC123 to log in, the code will expire in 300 seconds
Mär 15 10:49:12 fxlaptop mopidy[59707]: ERROR    2023-03-15 10:49:12,200 [59707:TidalBackend-9 (_actor_loop)] pykka
Mär 15 10:49:12 fxlaptop mopidy[59707]:   Unhandled exception in TidalBackend (urn:uuid:eb17025b-d5b1-4f83-bd25-ac1b9cbfc89d):
Mär 15 10:49:12 fxlaptop mopidy[59707]: Traceback (most recent call last):
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/usr/lib/python3.10/site-packages/pykka/_actor.py", line 186, in _actor_loop
Mär 15 10:49:12 fxlaptop mopidy[59707]:     self.on_start()
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/home/fx/.local/lib/python3.10/site-packages/mopidy_tidal/backend.py", line 83, in on_start
Mär 15 10:49:12 fxlaptop mopidy[59707]:     self.oauth_login_new_session(oauth_file)
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/home/fx/.local/lib/python3.10/site-packages/mopidy_tidal/backend.py", line 29, in oauth_login_new_session
Mär 15 10:49:12 fxlaptop mopidy[59707]:     self._session.login_oauth_simple(function=logger.info)
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/home/fx/.local/lib/python3.10/site-packages/tidalapi/session.py", line 323, in login_oauth_simple
Mär 15 10:49:12 fxlaptop mopidy[59707]:     future.result()
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 458, in result
Mär 15 10:49:12 fxlaptop mopidy[59707]:     return self.__get_result()
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/usr/lib64/python3.10/concurrent/futures/_base.py", line 403, in __get_result
Mär 15 10:49:12 fxlaptop mopidy[59707]:     raise self._exception
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
Mär 15 10:49:12 fxlaptop mopidy[59707]:     result = self.fn(*self.args, **self.kwargs)
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/home/fx/.local/lib/python3.10/site-packages/tidalapi/session.py", line 364, in _process_link_login
Mär 15 10:49:12 fxlaptop mopidy[59707]:     self.user = tidalapi.User(self, user_id=json['userId']).factory()
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/home/fx/.local/lib/python3.10/site-packages/tidalapi/user.py", line 48, in factory
Mär 15 10:49:12 fxlaptop mopidy[59707]:     return self.request.map_request('users/%s' % self.id, parse=self.parse)
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/home/fx/.local/lib/python3.10/site-packages/tidalapi/request.py", line 118, in map_request
Mär 15 10:49:12 fxlaptop mopidy[59707]:     return self.map_json(json_obj, parse=parse)
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/home/fx/.local/lib/python3.10/site-packages/tidalapi/request.py", line 125, in map_json
Mär 15 10:49:12 fxlaptop mopidy[59707]:     return parse(json_obj)
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/home/fx/.local/lib/python3.10/site-packages/tidalapi/user.py", line 65, in parse
Mär 15 10:49:12 fxlaptop mopidy[59707]:     return user.parse(json_obj)
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/home/fx/.local/lib/python3.10/site-packages/tidalapi/user.py", line 104, in parse
Mär 15 10:49:12 fxlaptop mopidy[59707]:     super(LoggedInUser, self).parse(json_obj)
Mär 15 10:49:12 fxlaptop mopidy[59707]:   File "/home/fx/.local/lib/python3.10/site-packages/tidalapi/user.py", line 77, in parse
Mär 15 10:49:12 fxlaptop mopidy[59707]:     self.picture_id = json_obj['picture']
Mär 15 10:49:12 fxlaptop mopidy[59707]: KeyError: 'picture'
Mär 15 10:49:12 fxlaptop mopidy[59707]: ERROR    2023-03-15 10:49:12,202 [59707:MainThread] mopidy.commands
Mär 15 10:49:12 fxlaptop mopidy[59707]:   Actor died: TidalBackend (urn:uuid:eb17025b-d5b1-4f83-bd25-ac1b9cbfc89d) stopped before handling the message
Mär 15 10:49:12 fxlaptop mopidy[59707]: INFO     2023-03-15 10:49:12,204 [59707:MainThread] mopidy.commands
```

**Comment by fmarzocca** [comment]
Confirm this issue. Same for me.

**Comment by fishbone1** [comment]
Hi, how can we apply this fix? Patch the local file?

**Comment by BlackLight** [comment]
@fishbone1 you can install mopidy-tidal from my fork:

```
pip install git+https://github.com/BlackLight/mopidy-tidal
```

Make sure to uninstall `tidalapi` first, as the pip force reinstall doesn't work very well when installing dependencies via git.

**Comment by fishbone1** [comment]
Thanks! In my case:

```
sudo pip3 uninstall tidalapi
sudo pip3 install git+https://github.com/BlackLight/mopidy-tidal
```

**Comment by tehkillerbee** [comment]
PR #99 by @BlackLight has now been merged into master. Closing this issue.
